[[Section::HLD::SoftwareArchitecture]]

== ad_rss_lib: Software Architecture

This section describes the software architecture of the ad_rss_lib in detail. The static view covers the deployed
artifacts, the interfaces and data types of the library. The dynamic view describes the behaviour of the library in more
detail.

=== Static View

[[Figure:ad_rss_lib]]
.The packages within the ad_rss_lib.
image::img/acd35c53-c5d6-4c0f-98f3-a8103f9afb91_url_1c58b101-7c5d-43da-95da-8a7d06752a22.tmp[caption="Figure {counter:figure}. "]

The ad_rss_lib is implemented in C++. Based on a set of datatype definitions the interfaces are provided to:

1. prepare the RSS situations between individual pairs of ego vehicle and objects
2. trigger the situation specific RSS calculations
3. resolve the situation specific responses to one global response
4. translate the global response into concrete restrictions of the actuator control commands

Finally, the implementation of the ad_rss_lib is deployed within a set of artifacts.

==== ExtLibs

==== Artifact Deployment

Definition of artifacts of the C++ library for RSS.

[[Figure:Artifact_Deployment]]
.Deployed artifacts of the C++ library for RSS.
image::img/554df18f-9dbf-4fef-90dd-199a37341089_url_edf573fb-eecc-4f56-a698-31871f3101ae.tmp[caption="Figure {counter:figure}. "]

===== ad_rss_lib

The whole ad_rss_lib implementation is deployed within one library artifact.

==== Interfaces

Definition of Interfaces provided within the ad_rss_lib implementation.

The ad_rss_lib is implemented as a whole within the namespace ad_rss.

===== Namespace ad_rss::core

Namespace for RSS core interfaces and operations.

This contains the interfaces including the operations the ad_rss_lib provides to the user to perform the RSS
functionality.

[[Figure:Namespace_ad_rss__core]]
.The core interfaces provided by the ad_rss_lib.
image::img/a5f7ccec-65c4-4059-82e3-d5628661b74a_url_77eaff39-2b9e-4e86-b372-fa86e91a9803.tmp[caption="Figure {counter:figure}. "]

====== RssCheck

Class providing the functionality of the RSS check sequence at once with the RSS world model as input and restrictions
of the acceleration for the actuator control as output. This class internally makes use of the RssSituationExtraction,
RssSituationChecking, RssResponseResolving and RssResponseTransformation functionality.

calculateAccelerationRestriction

Perform the calculation of the RSS checks on the current world model and provide the acceleration restriction for the
actuator control.

Returns true if the checks could be calculated, false if there was an error during the operation.

|====
|returns |bool |Out |False on failure.
|worldModel |WorldModel |In |The current world model information.
|accelerationRestriction |AccelerationRestriction |Out |The restrictions on the vehicle acceleration to become RSS safe.
|====

====== RssSituationExtraction

Class providing functions required for the extraction of the RSS situations from the RSS world model.

extractSituations

Extract all RSS situation pairs pair <ego-vehicle, object> to be checked from the world model.

Returns true if the situations could be created, false if there was an error during the operation.

|====
|returns |bool |Out |False on failure.
|worldModel |WorldModel |In |The current world model information.
|situationVector |SituationVector |Out |The vector of situations to be analyzed with RSS.
|====

extractSituation

Extract the RSS situation pair <ego-vehicle, object> of the ego vehicle and the object to be checked.

Returns true if the situation could be created, false if there was an error during the operation.

|====
|returns |bool |Out |False on failure.
|egoVehicle |Object |In |The information on the ego vehicle object.
|objectToBeChecked |Object |In |The information on the object to be checked.
|situation |Situation |Out |The situation to be analyzed with RSS.
|====

====== RssSituationChecking

Class providing functions required for the RSS checks of the situation.

checkSituations

Checks if the current situation pairs <ego-vehicle, object> are safe.

Returns true if the situations could be analyzed, false if an error occurred during evaluation.

|====
|returns |bool |Out |False on failure.
|situationVector |SituationVector |In |The vector of situations that should be analyzed.
|responseStateVector |ResponseStateVector |Out |The vector of response states for the current situations.
|====

checkSituation

Checks if the current situation pair <ego-vehicle, object> is safe.

Returns true if the situation could be analyzed, false if an error occurred during evaluation.

|====
|returns |bool |Out |False on failure.
|situation |Situation |In |The situation that should be analyzed.
|response |ResponseState |Out |The response state for the current situation.
|====

====== RssResponseResolving

Class to resolve the responseStateVector of the different situation specific responses into a single responseState. This
class tracks the RSS response state of every situation id over time and especially stores the respective response state
before the danger threshold time. This requires that the id of a RSS situation remains constant over time in case it
refers to the same object; otherwise tracking over time will fail.

provideProperResponse

Calculate the proper response from of the current situation pair <ego-vehicle, object> response states. It combines all
response states into one single overall RssResponse.

Returns true if the proper response state could be calculated, false otherwise.

|====
|returns |bool |Out |False on failure.
|currentResponseStateVector |ResponseStateVector |In |Vector with all the responses gather for the current individual
situations
|properResponseState |ResponseState |Out |The proper overall response state.
|====

====== RssResponseTransformation

Class providing functions required to transform the proper response into restrictions of the acceleration for the
actuator control.

transformProperResponse

Transform the proper response into restrictions of the acceleration for the actuator control. Since the
RssResponseResolving entity is acting within the situation coordinate system, it is not able to decide on the actual
lateral movement of the ego-vehicle within its lane. Within this function the required world model data is available to
decide if a desired lateral response can be resolved either by applying a restriction on the lateral acceleration or, in
addition, requires a restriction of the longitudinal acceleration.

Returns true if the acceleration restrictions could be calculated, false otherwise.

|====
|returns |bool |Out |False on failure.
|worldModel |WorldModel |In |The current world model information.
|response |ResponseState |In |The proper overall response to be transformed.
|accelerationRestriction |AccelerationRestriction |Out |The restrictions on the vehicle acceleration to become RSS safe.
|====

==== DataTypes

Definition of DataTypes used within the ad_rss_lib implementation.

The ad_rss_lib is implemented as a whole within the namespace ad_rss.

[[Figure:Namespace_ad_rss]]
.The RSS datatypes are organized within several sub-namespaces.
image::img/a706bfd6-0115-44ba-8e84-f81b7ad0de1c_url_ceb5d338-61b0-48c2-8fef-454c876a0067.tmp[caption="Figure {counter:figure}. "]

===== Namespace ad_rss::physics

Namespace for RSS physics datatypes.

This contains types declaring physical measures referring time, distance, speed and basic combinations of that like
ranges.

[[Figure:Namespace_ad_rss__physics]]
.The types describing the basic physics used within RSS implementation.
image::img/21af5c0d-86e6-4c86-b97d-c2389d81ef47_url_5568c8f3-101b-4900-9e3c-4571f72fe7c6.tmp[caption="Figure {counter:figure}. "]

====== Acceleration (Typedef)

The rate of change of (U) Speed of an object with respect to time.

Unit: meter per second squared

|====
|dimension |Acceleration
|unit |MeterPerSecondSquared
|float64_t |[ 1 ]
|====

====== AccelerationRange (Structure)

An acceleration range described by its borders: [minimum, maximum].

|====
|minimum |Acceleration |The minimum value of the acceleration range.
|maximum |Acceleration |The maximum value of the acceleration range.
|====

====== Distance (Typedef)

The length of a specific path traveled between two points.

Unit: meter

|====
|dimension |Length
|unit |Meter
|float64_t |[ 1 ]
|====

====== DistanceSquared (Typedef)

DistanceSquared represents a squared Distance.
Unit: square meter

|====
|unit |SquareMeter
|dimension |Area
|float64_t |[ 1 ]
|====

====== MetricRange (Structure)

A metric range described by its borders: [minimum, maximum].

|====
|minimum |Distance |The minimum value of the metric range.
|maximum |Distance |The maximum value of the metric range.
|====

====== Duration (Typedef)

A duration represents a time interval

Unit: second

|====
|unit |Second
|dimension |Time
|float64_t |[ 1 ]
|====

====== DurationSquared (Typedef)

DurationSquared represents a squared Duration
Unit: second^2

|====
|unit |SecondSquared
|float64_t |[ 1 ]
|====

====== ParametricValue (Typedef)

A parametric value in the range of [0.0; 1.0] describing the relative progress.

|====
|float64_t |[ 1 ]
|====

====== Speed (Typedef)

The rate of change of an object's position with respect to time. The speed of an object is the magnitude of its
velocity.

Unit: meter per second

|====
|dimension |Velocity
|unit |MeterPerSecond
|float64_t |[ 1 ]
|====

====== SpeedSquared (Typedef)

SpeedSquared represents a squared Speed.
Unit: square meter per second square

|====
|unit |SquareMeterPerSecondSquared
|float64_t |[ 1 ]
|====

====== ParametricRange (Structure)

A parametric range within a lane segment described by its borders: [minimum, maximum].

|====
|minimum |ParametricValue |The minimum value of the parametric range.
|maximum |ParametricValue |The maximum value of the parametric range.
|====

====== TimeIndex (Typedef)

Defines a certain point in time.

|====
|uint64_t |[ 1 ]
|====

====== CoordinateSystemAxis (Enumeration)

Enumeration defining the axis of the situation coordinate system.

|====
|Longitudinal |0 |longitudinal axis: ego vehicle is driving in positive direction
|Lateral |1 |lateral axis: ego vehicle left to right defines the positive direction
|====

===== Namespace ad_rss::world

Namespace for RSS world datatypes.

This contains types that are used to describe the local world model RSS is acting on. These describe the ego vehicle and
object states as well as the parts of the road network relevant to judge the situations between ego vehicle and the
objects.

[[Figure:Namespace_ad_rss__world_road_types]]
.The types describing the road and lane geometries used within the local RSS world model.
image::img/bb52ad9d-2e73-4798-ad3a-b90a4c2ebef4_url_8d6bc8ca-d720-4f28-92f7-c55cc88cf901.tmp[caption="Figure {counter:figure}. "]

[[Figure:Namespace_ad_rss__world_object_types]]
.The types describing the objects used within the local RSS world model.
image::img/42b62d1f-7e0d-4169-a37d-e1f2625d67d4_url_1a760d9a-6e9a-46a7-9a2e-20a10a9863d9.tmp[caption="Figure {counter:figure}. "]

[[Figure:Namespace_ad_rss__world]]
.The types describing the high level world model and object used within the local RSS world model.
image::img/bbb33dd2-4708-4291-bf4f-4d4fd0e46deb_url_25ed9391-a145-443d-919a-2e3479b78b54.tmp[caption="Figure {counter:figure}. "]

====== LaneSegmentId (Typedef)

Defines the unique id of a lane segment.

|====
|uint64_t |[ 1 ]
|====

====== LaneSegmentType (Enumeration)

|====
|Normal |0 |Normal lane segement. Nothing special to consider.
|Intersection |1 |Lane segment is intersecting with another lane segment of the intersecting road.
|====

====== LaneDrivingDirection (Enumeration)

|====
|Bidirectional |0 |Traffic flow in this lane segment is in both directions.
|Positive |1 |Nominal traffic flow in this lane segment is positive RoadArea direction.
|Negative |2 |Nominal traffic flow in this lane segment is negative RoadArea direction.
|====

====== LaneSegment (Structure)

Defines a lane segment.

|====
|id |LaneSegmentId |The id of the lane segment.
|type |LaneSegmentType |The type of this lane segment in context of the RssArea it belongs to.
|drivingDirection |LaneDrivingDirection |The nominal direction of the traffic flow of this lane segment in context of
the RssArea it belongs to.
|length |MetricRange |The metric range of the lane segments length.
|width |MetricRange |The metric range of the lane segments width.
|====

====== RoadSegment (Typedef)

A RoadSegment is defined by lateral neighboring lane segments. The lane segments within a road segment have to be
ordered from right to left in respect to the driving direction defined by the road area.

|====
|ad_rss::world::LaneSegment |[ * ]
|====

====== RoadArea (Typedef)

A RoadArea is defined by longitudinal neighboring road segments. The road segments within a road area have to be ordered
from start to end in respect to the driving direction.

|====
|ad_rss::world::RoadSegment |[ * ]
|====

====== Scene (Structure)

A Scene defines the relation between the ego vehicle and another object. It consists of the type of situation between
these two and the corresponding road areas of interest. All lane segments on the route between ego vehicle and the
object have to be part of this. RSS has to be able to calculate minimum and maximum distances between ego vehicle and
object as well as accelerated movements within this area.

|====
|situationType |SituationType |The type of the current situation. Depending on this type the other fields of the RssArea
might be left empty.
|egoVehicleRoad |RoadArea |The RssRoadArea the ego vehicle is driving in. The driving direction of the ego vehicle
define the ordering of the road segments. In non-intersection situations the object is also driving in this road area.
|intersectingRoad |RoadArea |The RssRoadArea an intersecting vehicle is driving in. The driving direction of the
intersecting vehicle define the ordering of the road segments. The road area should contain all neigboring lanes the
other vehcile is able to drive in.  In non-intersection situations this road area is empty.
|object |Object |The object this scene refers to.
|====

====== ObjectId (Typedef)

Defines the unique id of an object.

|====
|uint64_t |[ 1 ]
|====

====== ObjectType (Enumeration)

Enumeration describing the types of object.

|====
|EgoVehicle |0 |The object is the ego vehicle.
|OtherVehicle |1 |The object is some other real vehicle.
|ArtificialObject |2 |The object is an artificial one.
|====

====== OccupiedRegion (Structure)

Describes the region that an object covers within a lane segment.

An object on a lane is described by the parametric range it spans in each of the two lane segment directions.

|====
|segmentId |LaneSegmentId |The id of the lane segment this region refers to.
|lonRange |ParametricRange |The parametric range an object spans in longitudinal direction within a lane segment.
|latRange |ParametricRange |The parametric range an object spans in lateral direction within a lane segment.
|====

====== OccupiedRegionVector (Typedef)

A vector of occupied regions.

|====
|ad_rss::world::OccupiedRegion |[ * ]
|====

====== LongitudinalRssAccelerationValues (Structure)

Collection of the RSS acceleration values in longitudinal direction.

|====
|accelMax |Acceleration |Absolute amount of the maximum allowed acceleration.  This value has always to be positive,
zero is allowed.
|brakeMax |Acceleration |Absolute amount of the maximum allowed braking deceleration.  This value has always to be
positive and not smaller than brakeMin.
|brakeMin |Acceleration |Absolute amount of the minimum allowed breaking deceleration.  This value has always to be
positive and not smaller than brakeMinCorrect.
|brakeMinCorrect |Acceleration |Absolute amount of the minimum allowed breaking deceleration when driving on the correct
lane.  This value has always to be positive.
|====

====== LateralRssAccelerationValues (Structure)

Collection of the RSS acceleration values in lateral direction.

|====
|accelMax |Acceleration |Absolute amount of the maximum allowed acceleration. This value has always to be positive, zero
is allowed.
|brakeMin |Acceleration |Absolute amount of the minimum allowed breaking deceleration. This value has always to be
positive.
|====

====== Dynamics (Structure)

Describes the RSS dynamics values to be applied for an object within the metric world frame. The dynamics consist of a
longitudinal component, a lateral component and a lateral fluctuation margin to be taken into account to compensate for
lateral fluctuations.

|====
|alphaLon |LongitudinalRssAccelerationValues |RSS dynamics values along longitudinal coordinate system axis.
|alphaLat |LateralRssAccelerationValues |RSS dynamics values along lateral coordinate system axis.
|lateralFluctuationMargin |Distance |Defines the lateral fluctuation margin to be taken into account.
|====

====== Object (Structure)

An object is described by several aspects: the unique id of an object, the type of the object, the lane regions the
object occupies, the objects velocity within its lane and finally the area of interaction of ego vehicle and the object.

|====
|objectId |ObjectId |Defines the unique id of an object. This id has to be constant over time for the same object.
|objectType |ObjectType |Defines the type of the object.
|occupiedRegions |OccupiedRegionVector |Defines the lane regions the object occupies.
|dynamics |Dynamics |Defines the objects dynamics to be applied. This parameters are provided on a per object basis to
be able to adapt these e.g. in respect to object type or the weather conditions.
|velocity |Velocity |Defines the objects velocity in respect to its current major lane.
|responseTime |Duration |Defines the response time of the object within the current scene.
|====

====== WorldModel (Structure)

The world model, RSS requires as input, consists of the egoVehicle and object description as well as the list of
relevant lane segments.

|====
|timeIndex |TimeIndex |The time index is required to distinguish different points in time when tracking states or
transforming responses back. Each world model referring to another point in time should get another time index. The time
index of the world model must not be zero.
|egoVehicle |Object |The ego vehicle.
|scenes |SceneVector |All scenes
|====

====== AccelerationRestriction (Structure)

Defines restrictions of the vehicle acceleration.

|====
|timeIndex |TimeIndex |The time index these acceleration restrictions are referring to.
|lateralLeftRange |AccelerationRange |The range of the acceleration restriction in lateral left direction.
|longitudinalRange |AccelerationRange |The range of the acceleration restriction in longitudinal direction.
|lateralRightRange |AccelerationRange |The range of the acceleration restriction in lateral right direction.
|====

====== Velocity (Structure)

Defines the velocity of an object within its current lane. The velocity consists of a longitudinal and a lateral
component.

|====
|speedLon |Speed |The longitudinal speed component of the velocity vector.
The longitudinal component of the velocity is always measured tangential to the center line of the current lane.
|speedLat |Speed |The lateral speed component of the velocity vector.
The lateral component of the velocity is always measured orthogonal to the center line of the current lane.
|====

====== SceneVector (Typedef)

A vector of scenes.

|====
|ad_rss::world::Scene |[ * ]
|====

===== Namespace ad_rss::situation

Namespace for RSS situation datatypes.

This contains types that are used within the calculation of the RSS formulas which are performed within the situation
coordinate system.

[[Figure:Namespace_ad_rss__situation_vehicle_state]]
.The types describing the vehicle state used within the situation coordinate system.
image::img/22bc8a63-92f9-49d8-bd6b-3280c1111c96_url_1199fbbe-ee18-4782-a42e-ffda575214f5.tmp[caption="Figure {counter:figure}. "]

[[Figure:Namespace_ad_rss__situation]]
.The types describing a situation used within the situation coordinate system.
image::img/aea213de-619b-435a-9e52-18f48789cec2_url_11618db0-0356-416d-9658-b399f06658be.tmp[caption="Figure {counter:figure}. "]

====== VehicleState (Structure)

The state of an object in a RSS situation.

The state consists of the following components in respect to the situation coordinate system: the velocity, the distance
to the intersection (if applicable), the dynamics, the response time, a Right-of-Way priority flag as well as a flag
stating if the vehicle is driving in its correct lane.

|====
|velocity |Velocity |The situation specific velocity.
|dynamics |Dynamics |The situation specific dynamics.
|responseTime |Duration |The situation specific response time.
|hasPriority |bool |Flag indicating if the situation specific Right-of-Way relation.
|isInCorrectLane |bool |Flag indicating if the vehicle driving in the correct lane
|distanceToEnterIntersection |Distance |The minimum distance to be covered by the vehicle to enter the intersection.
|distanceToLeaveIntersection |Distance |The maximum distance to cover by the vehicle to leave the intersection
completely.
|====

====== SituationId (Typedef)

The unique id of an situation over time.

|====
|uint64_t |[ 1 ]
|====

====== SituationType (Enumeration)

Enumeration describing the type of situation.

|====
|NotRelevant |0 |The other vehicle cannot conflict with the ego vehicle. This kind of situations are always considered
to be safe. Use this situation state to make the object visible in the result vector to be a known object, but not
relevant for RSS (e.g. object in opposite direction, but already passed by).
|SameDirection |1 |Both drive on the same road in the same direction.
|OppositeDirection |2 |Both drive on the same road in the opposite direction.
|IntersectionEgoHasPriority |3 |Both drive on individual roads which intersect at the end. Ego vehicle has priority over
object.
|IntersectionObjectHasPriority |4 |Both drive on individual roads which intersect at the end. Object has priority over
ego vehicle.
|IntersectionSamePriority |5 |Both drive on individual roads which intersect at the end. Object and ego vehicle have
same priority.
|====

====== LateralRelativePosition (Enumeration)

Enumeration describing the relative lateral position between two objects, a and b, within their situation coordinate
system.

|====
|AtLeft |0 |The object a is completely left of object b. This means there is an actual lateral space between them.
|OverlapLeft |1 |The objects overlap. The left border of object a is left of the left border of object b AND the right
border of object a is left of the right border of object b.
|Overlap |2 |The objects overlap, but neither the conditions for OverlapLeft nor OverlapRight are applicable.
|OverlapRight |3 |The objects overlap. The left border of object a is right of the left border of object b AND the right
border of object a is right of the right border of object b.
|AtRight |4 |The object a is completely right of object b. This means there is an actual lateral space between them.
|====

====== LongitudinalRelativePosition (Enumeration)

Enumeration describing the relative longitudinal position between two objects, a and b, within their situation
coordinate system.

|====
|InFront |0 |The object a is completely in front of object b. This means there is an actual longitudinal space between
them.
|OverlapFront |1 |The objects overlap. The front border of object a is in front of the front border of object b AND the
back border of object a is in front of the back border of object b.
|Overlap |2 |The objects overlap, but neither the conditions for OverlapFront nor OverlapBack are applicable.
|OverlapBack |3 |The objects overlap. The front border of object a is at back of the front border of object b AND the
back border of object a is at back of the back border of object b.
|AtBack |4 |The object a is completely at back of object b. This means there is an actual longitudinal space between
them.
|====

====== RelativePosition (Structure)

Describes the relative position between two objects within their situation coordinate system.

|====
|longitudinalPosition |LongitudinalRelativePosition |The longitudinal relative position between to objects within their
situation coordinate system.
|longitudinalDistance |Distance |The longitudinal distance between the two objects within their situation coordinate
system.
|lateralPosition |LateralRelativePosition |The lateral relative position between to objects within their situation
coordinate system.
|lateralDistance |Distance |The lateral distance between the two objects within their situation coordinate system.
|====

====== Situation (Structure)

Describes a RSS situation.

A situation always considers the relative relation between two objects: the ego vehicle and one other vehicle. The
situation coordinate system is unique for one specific situation. As a consequence the vehicle state of the ego vehicle
in different RSS situations cannot be compared to each other. Consists of a situation id and type, the VehicleState of
the ego vehicle, the VehicleState of the other vehicle and the RelativePosition between ego vehicle and other vehicle.

|====
|timeIndex |TimeIndex |The time index is required to distinguish different points in time when tracking states or
transforming responses back.
|situationId |SituationId |The unique id of the situation.The situation id has to be constant over time for a pair of
ego vehicle and specific other vehicle.
E.g. might be filled with an id identifying the other vehicle unambiguously.
|situationType |SituationType |The type of the current situation.
|egoVehicleState |VehicleState |The vehicle state of the ego vehicle
|otherVehicleState |VehicleState |The vehicle state of the other vehicle within the situation.
|relativePosition |RelativePosition |The relative position between the ego vehicle and the other vehicle within this
situation.
|====

====== SituationVector (Typedef)

A vector of situations.

|====
|ad_rss::situation::Situation |[ * ]
|====

===== Namespace ad_rss::state

Namespace for RSS state datatypes.

This contains types used in conjunction with the RSS state and responses.

[[Figure:Namespace_ad_rss__state]]
.The types describing the RSS response and the RSS state.
image::img/28c0e20e-96e6-4571-a5c5-d0984499794c_url_7a1cc948-6c7c-4549-8f6b-ab2575bcd8e6.tmp[caption="Figure {counter:figure}. "]

====== LongitudinalResponse (Enumeration)

Enumeration defining the possible longitudinal responses.

Be aware: there has to be a strict order of the enumeration values according to the strictness of the response.

|====
|None |0 |No action required.
|BrakeMinCorrect |1 |Vehicle has to decerate at least with brake min correct longitudinally
|BrakeMin |2 |Vehicle has to decerate at least with brake min longitudinally
|====

====== LateralResponse (Enumeration)

Enumeration defining the possible lateral responses.

Be aware: there has to be a strict order of the enumeration values according to the strictness of the response.

|====
|None |0 |No action required.
|BrakeMin |1 |Vehicle has to decerate at least with brake min laterally
|====

====== LongitudinalRssState (Structure)

Struct to store the longitudinal RSS state.

|====
|isSafe |bool |Flag to indicate if the state is longitudinal safe.
|response |LongitudinalResponse |required response in longitudinal direction
|====

====== LateralRssState (Structure)

Struct to store the lateral RSS state.

|====
|isSafe |bool |Flag to indicate if the state is lateral safe.
|response |LateralResponse |required response in lateral direction
|====

====== ResponseState (Structure)

Struct defining the RSS state of a single object.

|====
|timeIndex |TimeIndex |The time index is required to distinguish different points in time when tracking states or
transforming responses back.
|situationId |SituationId |Id of the situation this state refers to.The id has to remain unique over time representing
the situation (ego-vehicle / object pair) under investigation.
It is used to track the state of the ego-vehicle / object constellation i.e. at point of danger threshold time.
|longitudinalState |LongitudinalRssState |The current longitudinal rss state.
|lateralStateRight |LateralRssState |The current lateral rss state at right side in respect to ego-vehicle driving
direction.
|lateralStateLeft |LateralRssState |The current lateral rss state at left side in respect to ego-vehicle driving
direction.
|====

====== ResponseStateVector (Typedef)

A vector of response states.

|====
|ad_rss::state::ResponseState |[ * ]
|====

=== Dynamic View

[[Figure:RssSubsystemChecker]]
.RSS internal processing steps to perform RSS checks and execute the RSS proper response
image::img/910dab27-21e0-4116-857d-f1d21288873c_url_8c31bedf-464a-4305-800c-c034635e8a7f.tmp[caption="Figure {counter:figure}. "]

The RssSubsystem realizes the RSS part functionality. It implements the RSS checks based on the RssWorldModelData
received from the SensorSubsystem:

1. Keep a safe distance from the car in front
2. Leave time and space for others in lateral maneuvers
3. Exhibit caution in occluded areas [not implemented yet]
4. Right-of-Way is given, not taken

In case a dangerous situation is detected a respective proper response is calculated and the actuator control commands
received
from the PlanningSubsystem are restricted accordingly to realize planning safety.

==== RssSituationExtractionImpl

RssSituationExtractionImpl describes the implementation of the RssSituationExtraction entity by defining a statechart.

[[Figure:RssSituationExtractionImpl]]
.Statechart Diagram describing the dynamic behavior of the RssSituationExtraction entity.
image::img/0ff5f626-913b-4587-bdc8-48f95424bb7e_url_c3a2bf7d-ae8f-4c0a-8f34-3e2dacbc628f.tmp[caption="Figure {counter:figure}. "]

The following table describes the events, triggers, states and their transitions of the statechart in detail.

|====
|Event/Trigger |Argument Type |Argument |Description

|evRssWorldModel |WorldModel |worldModel |Event trigged when RssWorldModel data is received at the input.
|====

|====
|State |Transition |Target State |Description

|idle | | |Idle state. Waiting for input data.
|  -> |evRssWorldModel |extractSituations |WorldModel data received.
|extractSituations | | |All input data received. Perform operation to extract situations.
|  -> | |checkOperationResult |
|error | | |Final error state.
|====

==== RssSituationCheckingImpl

RssSituationCheckingImpl describes the implementation of the RssSituationChecking entity by defining a statechart.

[[Figure:RssSituationCheckingImpl]]
.Statechart Diagram describing the dynamic behavior of the RssSituationChecking entity.
image::img/9bf429cc-bff9-4926-8c36-9ffc69b145c3_url_1906bcfc-37d8-4c01-9ad3-323566ac41eb.tmp[caption="Figure {counter:figure}. "]

The following table describes the events, triggers, states and their transitions of the statechart in detail.

|====
|Event/Trigger |Argument Type |Argument |Description

|evRssSituationVector |SituationVector |situationVector |Event trigged when RssSituationVector data is received at the
input.
|====

|====
|State |Transition |Target State |Description

|idle | | |Idle state. Waiting for input data.
|  -> |evRssSituationVector |checkSituations |SituationVector data received.
|checkSituations | | |All input data received. Perform operation to check situations.
|  -> | |checkOperationResult |
|error | | |Final error state.
|====

==== RssResponseResolvingImpl

RssResponseResolvingImpl describes the implementation of the RssResponseResolving entity by defining a statechart.

[[Figure:RssResponseResolvingImpl]]
.Statechart Diagram describing the dynamic behavior of the RssResponseResolving entity.
image::img/e520bc5e-de98-43c6-87fd-3183af43f7ad_url_90a67595-90ac-4041-99ab-a1852fbafc1c.tmp[caption="Figure {counter:figure}. "]

The following table describes the events, triggers, states and their transitions of the statechart in detail.

|====
|Event/Trigger |Argument Type |Argument |Description

|evRssResponseStateVector |ResponseStateVector |responseStateVector |Event trigged when RssResponseStateVector data is
received at the input.
|====

|====
|State |Transition |Target State |Description

|idle | | |Idle state. Waiting for input data.
|  -> |evRssResponseStateVector |resolveResponse |ResponseStateVector data received.
|resolveResponse | | |All input data received. Perform operation to resolve responses.
|  -> | |checkOperationResult |
|error | | |Final error state.
|====

==== RssResponseTransformationImpl

RssResponseTransformationImpl describes the implementation of the RssResponseTransformation entity by defining a
statechart.

[[Figure:RssResponseTransformationImpl]]
.Statechart Diagram describing the dynamic behavior of the RssResponseTransformation entity.
image::img/7b59d685-6c32-4fcc-91c3-d5118e5cfd3e_url_08e9e39b-f00b-4b0f-b70f-e39ea2347be4.tmp[caption="Figure {counter:figure}. "]

The following table describes the events, triggers, states and their transitions of the statechart in detail.

|====
|Event/Trigger |Argument Type |Argument |Description

|evRssResponseState |ResponseState |responseState |Event trigged when RssResponseState data is received at the input.
|evRssWorldModel |WorldModel |worldModel |Event trigged when RssWorldModel data is received at the input.
|====

|====
|State |Transition |Target State |Description

|idle | | |Idle state. Waiting for input data.
|  -> |evRssWorldModel |worldModelDataAvailable |WorldModel data received.
|  -> |evRssResponseState |responseStateAvailable |ResponseState data received.
|worldModelDataAvailable | | |World model data received. Still waiting for response states.
|  -> |evRssResponseState |transformResponse |ResponseState data received.
|responseStateAvailable | | |Response state data received. Still waiting for world model.
|  -> |evRssWorldModel |transformResponse |WorldModel data received.
|transformResponse | | |All input data received. Perform operation to transform response.
|  -> | |checkOperationResult |
|error | | |Final error state.
|====
