[[Section::HLD::SoftwareArchitecture]]

== ad-rss-lib: Software Architecture

This section describes the software architecture of the ad-rss-lib in detail. The static view covers the deployed
artifacts, the interfaces and data types of the library. The dynamic view describes the behaviour of the library in more
detail.

=== Static View

[[Figure:ad_rss_lib]]
.The packages within the ad-rss-lib.
image::img/3215dc26-cb11-4d2a-bee0-5bce35dc7d8a_url_30dce600-cb20-4ebb-9cd6-e2b2d333579c.tmp[caption="Figure {counter:figure}. "]

The ad-rss-lib is implemented in C++. Based on a set of datatype definitions the interfaces are provided to:

1. prepare the RSS situations between individual pairs of ego vehicle and objects
2. trigger the situation specific RSS calculations
3. resolve the situation specific responses to one global response
4. translate the global response into concrete restrictions of the actuator control commands

Finally, the implementation of the ad-rss-lib is deployed within one library artifact named ad-rss-lib.

==== Interfaces

Definition of Interfaces provided within the ad-rss-lib implementation.

The ad-rss-lib is implemented as a whole within the namespace ad_rss.

===== Namespace ad_rss::core

Namespace for RSS core interfaces and operations.

This contains the interfaces including the operations the ad-rss-lib provides to the user to perform the RSS
functionality.

====== RssCheck

Class providing the functionality of the RSS check sequence at once with the RSS world model as input and restrictions
of the acceleration for the actuator control as output. This class internally makes use of the RssSituationExtraction,
RssSituationChecking, RssResponseResolving and RssResponseTransformation functionality.

calculateAccelerationRestriction

Perform the calculation of the RSS checks on the current world model and provide the acceleration restriction for the
actuator control.

Returns true if the checks could be calculated, false if there was an error during the operation.

|====
|returns |bool |Out |False on failure.
|worldModel |WorldModel |In |The current world model information.
|accelerationRestriction |AccelerationRestriction |Out |The restrictions on the vehicle acceleration to become RSS safe.
|====

====== RssSituationExtraction

Class providing functions required for the extraction of the RSS situations from the RSS world model.

extractSituations

Extract all RSS situation pairs pair <ego-vehicle, object> to be checked from the world model.

Returns true if the situations could be created, false if there was an error during the operation.

|====
|returns |bool |Out |False on failure.
|worldModel |WorldModel |In |The current world model information.
|situationVector |SituationVector |Out |The vector of situations to be analyzed with RSS.
|====

====== RssSituationChecking

Class providing functions required for the RSS checks of the situation.

checkSituations

Checks if the current situation pairs <ego-vehicle, object> are safe.

Returns true if the situations could be analyzed, false if an error occurred during evaluation.

|====
|returns |bool |Out |False on failure.
|situationVector |SituationVector |In |The vector of situations that should be analyzed.
|responseStateVector |ResponseStateVector |Out |The vector of response states for the current situations.
|====

====== RssResponseResolving

Class to resolve the responseStateVector of the different situation specific responses into a single responseState. This
class tracks the RSS response state of every situation id over time and especially stores the respective response state
before the danger threshold time. This requires that the id of a RSS situation remains constant over time in case it
refers to the same object; otherwise tracking over time will fail.

provideProperResponse

Calculate the proper response from of the current situation pair <ego-vehicle, object> response states. It combines all
response states into one single overall RssResponse.

Returns true if the proper response state could be calculated, false otherwise.

|====
|returns |bool |Out |False on failure.
|currentStates |ResponseStateVector |In |Vector with all the responses gather for the current situations
|responseState |ResponseState |Out |The proper overall response state.
|====

====== RssResponseTransformation

Class providing functions required to transform the proper response into restrictions of the acceleration for the
actuator control.

transformProperResponse

Transform the proper response into restrictions of the acceleration for the actuator control. Since the
RssResponseResolving entity is acting within the situation coordinate system, it is not able to decide on the actual
lateral movement of the ego-vehicle within its lane. Within this function the required world model data is available to
decide if a desired lateral response can be resolved either by applying a restriction on the lateral acceleration or, in
addition, requires a restriction of the longitudinal acceleration.

Returns true if the acceleration restrictions could be calculated, false otherwise.

|====
|returns |bool |Out |False on failure.
|worldModel |WorldModel |In |The current world model information.
|response |ResponseState |In |The proper overall response to be transformed.
|accelerationRestriction |AccelerationRestriction |Out |The restrictions on the vehicle acceleration to become RSS safe.
|====

==== DataTypes

Definition of DataTypes used within the ad-rss-lib implementation.

The ad-rss-lib is implemented as a whole within the namespace ad_rss.

[[Figure:Namespace_ad_rss]]
.The RSS datatypes are organized within several sub-namespaces.
image::img/1dab8fd5-c1cf-4a62-9232-66e2e9279428_url_c4da4d92-8fec-4665-bd03-914ad6ba8238.tmp[caption="Figure {counter:figure}. "]

For a detailed explanation of the individual types, please have a look into the doxygen documentation (https://intel.github.io/ad-rss-lib/doxygen/index.html).

===== Namespace ad_rss::physics

Namespace for RSS physics datatypes.

This contains types declaring physical measures referring time, distance, speed and basic combinations of that like
ranges.

===== Namespace ad_rss::world

Namespace for RSS world datatypes.

This contains types that are used to describe the local world model RSS is acting on. These describe the ego vehicle and
object states as well as the parts of the road network relevant to judge the situations between ego vehicle and the
objects.

===== Namespace ad_rss::situation

Namespace for RSS situation datatypes.

This contains types that are used within the calculation of the RSS formulas which are performed within the situation
coordinate system.

===== Namespace ad_rss::state

Namespace for RSS state datatypes.

This contains types used in conjunction with the RSS state and responses.

=== Dynamic View

[[Figure:RssSubsystemChecker]]
.RSS internal processing steps to perform RSS checks and execute the RSS proper response
image::img/ef40ca1b-866b-44e8-8e6d-a3d235c569e9_url_5931b775-17c8-4d95-ad51-e9e5c3cf8e76.tmp[caption="Figure {counter:figure}. "]

The RssSubsystem realizes the RSS part functionality. It implements the RSS checks based on the RssWorldModelData
received from the SensorSubsystem:

1. Keep a safe distance from the car in front
2. Leave time and space for others in lateral maneuvers
3. Exhibit caution in occluded areas [not implemented yet]
4. Right-of-Way is given, not taken

In case a dangerous situation is detected a respective proper response is calculated and the actuator control commands
received
from the PlanningSubsystem are restricted accordingly to realize planning safety.

==== RssSituationExtractionImpl

RssSituationExtractionImpl describes the implementation of the RssSituationExtraction entity by defining a statechart.

[[Figure:RssSituationExtractionImpl]]
.Statechart Diagram describing the dynamic behavior of the RssSituationExtraction entity.
image::img/33056e83-b4eb-47a3-98a5-0e762dcdd0f0_url_ef104650-716f-4190-bef9-9685cfaea8b7.tmp[caption="Figure {counter:figure}. "]

The following table describes the events, triggers, states and their transitions of the statechart in detail.

|====
|Event/Trigger |Argument Type |Argument |Description

|evRssWorldModel |WorldModel |worldModel |Event trigged when RssWorldModel data is received at the input.
|====

|====
|State |Transition |Target State |Description

|idle | | |Idle state. Waiting for input data.
|  -> |evRssWorldModel |extractSituations |WorldModel data received.
|extractSituations | | |All input data received. Perform operation to extract situations.
|  -> | |checkOperationResult |
|error | | |Final error state.
|====

==== RssSituationCheckingImpl

RssSituationCheckingImpl describes the implementation of the RssSituationChecking entity by defining a statechart.

[[Figure:RssSituationCheckingImpl]]
.Statechart Diagram describing the dynamic behavior of the RssSituationChecking entity.
image::img/6bded48d-c54a-4c10-ba6e-564a9047b27b_url_4ee9d29c-aced-4c30-a94b-e18f0def895d.tmp[caption="Figure {counter:figure}. "]

The following table describes the events, triggers, states and their transitions of the statechart in detail.

|====
|Event/Trigger |Argument Type |Argument |Description

|evRssSituationVector |SituationVector |situationVector |Event trigged when RssSituationVector data is received at the
input.
|====

|====
|State |Transition |Target State |Description

|idle | | |Idle state. Waiting for input data.
|  -> |evRssSituationVector |checkSituations |SituationVector data received.
|checkSituations | | |All input data received. Perform operation to check situations.
|  -> | |checkOperationResult |
|error | | |Final error state.
|====

==== RssResponseResolvingImpl

RssResponseResolvingImpl describes the implementation of the RssResponseResolving entity by defining a statechart.

[[Figure:RssResponseResolvingImpl]]
.Statechart Diagram describing the dynamic behavior of the RssResponseResolving entity.
image::img/841e0fb8-7627-4e1a-93d5-be6a40d71719_url_297d209b-1f20-4dd1-9461-425e2c4fb20c.tmp[caption="Figure {counter:figure}. "]

The following table describes the events, triggers, states and their transitions of the statechart in detail.

|====
|Event/Trigger |Argument Type |Argument |Description

|evRssResponseStateVector |ResponseStateVector |responseStateVector |Event trigged when RssResponseStateVector data is
received at the input.
|====

|====
|State |Transition |Target State |Description

|idle | | |Idle state. Waiting for input data.
|  -> |evRssResponseStateVector |resolveResponse |ResponseStateVector data received.
|resolveResponse | | |All input data received. Perform operation to resolve responses.
|  -> | |checkOperationResult |
|error | | |Final error state.
|====

==== RssResponseTransformationImpl

RssResponseTransformationImpl describes the implementation of the RssResponseTransformation entity by defining a
statechart.

[[Figure:RssResponseTransformationImpl]]
.Statechart Diagram describing the dynamic behavior of the RssResponseTransformation entity.
image::img/97f474d5-a4f5-4a3d-9733-cfc543afacf3_url_cb9fc4f4-f5d4-47eb-b3a5-d46e799422fb.tmp[caption="Figure {counter:figure}. "]

The following table describes the events, triggers, states and their transitions of the statechart in detail.

|====
|Event/Trigger |Argument Type |Argument |Description

|evRssResponseState |ResponseState |responseState |Event trigged when RssResponseState data is received at the input.
|evRssWorldModel |WorldModel |worldModel |Event trigged when RssWorldModel data is received at the input.
|====

|====
|State |Transition |Target State |Description

|idle | | |Idle state. Waiting for input data.
|  -> |evRssWorldModel |worldModelDataAvailable |WorldModel data received.
|  -> |evRssResponseState |responseStateAvailable |ResponseState data received.
|worldModelDataAvailable | | |World model data received. Still waiting for response states.
|  -> |evRssResponseState |transformResponse |ResponseState data received.
|responseStateAvailable | | |Response state data received. Still waiting for world model.
|  -> |evRssWorldModel |transformResponse |WorldModel data received.
|transformResponse | | |All input data received. Perform operation to transform response.
|  -> | |checkOperationResult |
|error | | |Final error state.
|====
